include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/src/solar_iconkit_data.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - unnecessary_this
